### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [innative-sdk/innative#14]
Would you like to [add more error handling](https://github.com/innative-sdk/innative/blob/5a4d75ec965b1a13390a1d365ea9cc8915a38af7/innative/util.cpp#L40 "Update candidate: __WASM_ALLOCATOR::allocate()") for return values from calls of a function like “[malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation")”?

**Comment by blackhole12** [comment]
It is not possible to fully address out of memory issues, because standard C++ functions simply throw an exception if there is a bad allocation, and certain situations make it almost impossible to do anything other than immediately abort execution. I have added checks that ensure any NULL values returned from an allocation will immediately abort the program so that nobody gets confused about random null dereference errors in case of an out of memory error.

**Comment by elfring** [comment]
Thanks for your source code improvement.

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by blackhole12** [comment]
Normally I run Visual Studio's static analysis, but that's not compatible with `v141_xp`, so instead I just ran cppcheck, which only found 1 error.
