### ISSUE TITLE
Broken linkage when using multiple embeddings

### ISSUE THREAD

**Issue by smatcher** [innative-sdk/innative#22]
Hi, 

I have a minimal repro for a bug that causes Innative to generate broken dlls
[BugEmbeddingInnative.zip](https://github.com/innative-sdk/innative/files/3703712/BugEmbeddingInnative.zip)
run build.bat to build the demo (it assumes that the sdk is next to the project folder) and run host.exe to test it.
it creates a working and a broken module, the difference is only whether or not we link and use functions from an external library.

Here is the DllEntryPoint as shown in IDA for both modules
Working module
![ok_module](https://user-images.githubusercontent.com/460855/66417677-d1aa2880-ea00-11e9-8d1a-5b43f933ec79.png)

Broken module
![broken_module](https://user-images.githubusercontent.com/460855/66417682-d53daf80-ea00-11e9-9585-965a0d5c89a5.png)

As you can see on the second one, all the call instructions are broken.

**Comment by blackhole12** [comment]
This appears like it might actually be a bug with clang. I need to update inNative's fork of LLVM to the latest version to try to rule out any bugs that might already have been fixed before I can continue investigating this,

**Comment by blackhole12** [comment]
While this bug is non-deterministic with the provided repro, I was able to narrow it down to **clang compiled embeddings only**. If the embedding is built using MSVC, the bug never happens. Since the standard inNative embedding is built using MSVC, this strongly suggests that there is either an incompatibility between MSVC and clang, or the static library being produced by clang is somehow triggering a bug in LLD.

**Comment by blackhole12** [comment]
**This is not a bug.** The actual problem here is how you are compiling the static library - namely, you are not actually compiling a static library, you are compiling a `.obj` file and renaming it a `.lib` file, which is not the same thing. LLD correctly identifies the file as an object file and not a static library, which allows the compilation to succeed but for whatever reason generates illegal code when handed a raw object file on windows. This is likely an unsupported situation in LLD, because the raw object file is not from the same compilation environment as the webassembly object files, and LLD doesn't realize it needs to relocate the functions. Wrapping the object file in a static library ensures LLD properly relocates the functions.

To correctly build a static library with clang on windows, use `llvm-lib.exe`:
```
set CLANG=clang.exe
set LIB=llvm-lib.exe
set INNATIVE_PATH=..\innative-windows-sdk-x64

set EMBEDDED=embedded.lib
%CLANG% -c src/embedded/fac.c -o %EMBEDDED%
%LIB% %EMBEDDED% /OUT:embedded.lib
```

Likewise, when building on Linux, please ensure you are archiving the `.o` files into a proper `.a` archive. inNative only supports linking static libraries as custom embedding environments, not raw object files.

**Comment by smatcher** [comment]
Thank you for investigating this.
