### ISSUE TITLE
Question regarding _innative_to_c

### ISSUE THREAD

**Issue by smatcher** [innative-sdk/innative#23]
Hi,
I do have a question regarding conversion between linear memory addresses and C addresses.

Say I have an embedding library that exposes a print function. `void print(const char*)`

The wasm binary relies on the following import 
```
(type (;0;) (func (param i32)))
(import "env" "print" (func (;0;) (type 0)))
```

If I just call print like this from wasm `print("Hello, world!");`
The print function is called with the address in linear memory, unfortunately I didn't find a way to implement the conversion from linear memory to the actual address space from inside the embedding library.
There is the helper function _innative_to_c but it's an intrisic that is only usable in wasm code.

So, at the moment the only way I found to make this work is to change the print function signature to take a i64 parameter and have the wasm module do the conversion like so `print(_innative_to_c("Hello, world!"));`

But this comes with a few caveats
- We need to write the call to the _innative_to_c function each time (I don't really want to impose this constraint on whoever writes a wasm module for my app)
- We need to disable ENV_CHECK_MEMORY_ACCESS and whitelist _innative_to_c  (I don't want to compromise on sandboxing or expose to much to the wasm module)

Is there a way to do that conversion from the embedding library ? conceptually it would make more sense since the API we expose to the wasm code only deals with linear memory.

**Comment by blackhole12** [comment]
This is a fundamental limitation of WebAssembly right now due to the lack of WebIDL bindings that support translating things to C pointers, although the proposal to add this [keeps changing every 3 months](https://github.com/WebAssembly/interface-types/blob/master/proposals/interface-types/Explainer.md). inNative actually does [contain a workaround](https://github.com/innative-sdk/innative/wiki/inNative-cref-Extension) for exactly this problem, but it is unlikely to help in your case because it requires unsupported WebAssembly instructions in the WebAssembly module. [Reference types](https://github.com/WebAssembly/reference-types) might theoretically make it possible to solve this without compromising the sandbox, but would still require writing a translation call every single time.

There **is** a proper solution to this that you can implement from your embedding library. You have to re-implement [your own version](https://github.com/innative-sdk/innative/wiki/Create-Custom-Environments#exporting-c-functions) of `printf` that takes a raw WebAssembly `i32` value, queries the WebAssembly memory pointer, and adds the `i32` value to that pointer. You can either require the webassembly module to export it's memory and use `LoadGlobal()` to get the pointer, or you can manually query the memory symbol yourself using the standard `[module]_linearmemory#0` naming convention.
```
IRExports exports;
innative_runtime(&exports);
auto export = (*exports.LoadGlobal)(ptr_binary, "module_name", "expected_memory_name");
void* mem = NULL;
if(export != NULL)
  mem = export->memory;
```
However, I checked the code and I don't think inNative exports the memories by default anymore. If requiring the modules to export their memories is not suitable, I can add a flag that exports all memories using the standard naming scheme.

**Comment by smatcher** [comment]
Thank you for your reply.
I managed to make both workaround work.

In my sample application I did automate the cref solution to some extent by doing the following
1. create a first environment
2. call AddModule with the source wasm
3. use innative_serialize_module to convert to wat
4. patch the signature of the functions that should use cref
5. create a second environment
6. load and use the patched wat module 

While doing so I noticed that innative_serialize_module doesn't really allow serializing to ram, supporting this would quite a trivial change.
Also, I didn't dig too much into this but it would be nice to be able to specify instructions for tweaking the signature of selected imports at the environment level. The interface could work a bit like the whitelist.
`(*exports.AddSignatureOverride)(env, "env", "my_function", "(param cref) (param i32) (result cref)");`
The actual implementation for doing the substitution while parsing the module ... is a whole other beast I admit.
This would make the whole 'creating 2 environments, serializing to wat and patching the resulting text file' unnecessary.

The LoadGlobal method works as well. At least in the version that I am using (tag v.0.1.2), the memory global is indeed exported.
My embedding library is dynamically shared with the host so I can call a setup function and send the memory pointer though it. The functions that the embedding library exposes to wasm all use this value to convert the pointers. You did mention that the dereference is needed in case the webassembly module expands its memory. I suppose this means that the "export->memory" pointer changes while the "export" pointer itself remains valid? Considering that "LoadGlobal" is basically a GetProcAddress with the correct symbol name this makes sense, but it doesn't hurt to ask ;)

Thanks again for your help.

**Comment by blackhole12** [comment]
Converting to wat and converting back is not necessary, because `cref` has a source representation [accessible from the schema.h header](https://github.com/innative-sdk/innative/blob/master/include/innative/schema.h#L48). Once you load any WebAssembly module, you can manually edit the function in the in-memory representation of the module and then recompile the environment without needing to create a second environment. I could still add serializing to RAM as a feature, but it really shouldn't be necessary.

> Also, I didn't dig too much into this but it would be nice to be able to specify instructions for tweaking the signature of selected imports at the environment level

Again, you can already do this. You are free to modify any module inside the environment and recompile it as you wish. This is why `schema.h` is provided in the publicly distributed header files. It describes the C API representation of the WebAssembly module and lets you modify any part of it.

> I suppose this means that the "export->memory" pointer changes while the "export" pointer itself remains valid? 

Yes, the `export` pointer is always valid, the `export->memory` pointer should always be reloaded at the start of every function, or after any action that could have caused a memory reallocation in the WebAssembly module.

**Comment by smatcher** [comment]
I didn't realize everything was exposed through schema.
This is cool, I managed to make it work that way. It's probably the cleanest way to do this. 👍 

However, while the data structure is exposed through schema.h,  the allocator and all the utility functions for inserting into these structures aren't. I'm fine with that  but it would be cool if this was exposed though.

**Comment by blackhole12** [comment]
It's not totally clear how all the utility functions should be exposed (or even which ones) for manipulating the schema, so I've created an issue to figure this out: #24
