### ISSUE TITLE
Problem using "_innative_funcptr"

### ISSUE THREAD

**Issue by EricSivilog** [innative-sdk/innative#25]
Sorry for the cross-post with the Discord channel but I thought it might be better for InNative users to see this discussion here.
I am currently trying to get a pointer to a function that resides in a WASM module so that it can be called back by a C module. I used the "_innative_funcptr" function to get a C-style pointer from within my WASM module, but it always returns ERR_INVALID_ARGUMENT_TYPE instead of the expected pointer.
Tracing into the code, I found that the cast "auto v = llvm::dyn_cast<llvm::ConstantInt, llvm::Value>(params[0]);" done in "innative::code::IN_Intrinsic_FuncPtr" always failed.
Here is (part of) the WAT code I am using (made it dead simple while debugging, just trying to access the 7th function in the module - the "final" aim is actually to call another C-function with the correct i64 pointer as a parameter...).

```
  (type (;6;) (func (param i32) (result i64)))
  (type (;9;) (func (result i32)))
  (import "env" "_innative_funcptr" (func $_innative_funcptr (type 6)))

  (func $do_simple_test(type 9) (result i32)
    (local i32 i32)
    i32.const 0
    local.set 0
    i32.const 7
    local.set 1
    local.get 1
    call $_innative_funcptr
    drop
    local.get 0
    return)
```

It looks like LLVM does not consider the parameter passed to _innative_funcptr as a constant (which is not totally wrong!). However, I don't understand how to make this work - hope someone can help!

**Comment by blackhole12** [comment]
The issue is here:
```
    i32.const 7
    local.set 1
    local.get 1```
You essentially push a constant, use it to set a local, then get the local instead of the constant. Because it's a local, inNative can't prove that it was a constant, so LLVM correctly says it isn't a constant. `_innative_funcptr` is currently limited to pure constants because it can't resolve the function pointers at runtime, at least right now. I may add a metadata table to the binary to lift this requirement, but for the moment, you should simply do this:
```
(type (;6;) (func (param i32) (result i64)))
  (type (;9;) (func (result i32)))
  (import "env" "_innative_funcptr" (func $_innative_funcptr (type 6)))

  (func $do_simple_test(type 9) (result i32)
    (local i32 i32)
    i32.const 0
    local.set 0
    i32.const 7
    call $_innative_funcptr
    drop
    local.get 0
    return)```

**Comment by EricSivilog** [comment]
Thanks a lot for your prompt answer which confirms what I suspected (sorry for not finding the issue myself, I am not very familiar with WebAssembly yet !).
Now the issue I have is that the WAT excerpt I gave above was created by compiling some C code through clang + wasm-ld. I did many tests to get the result you suggest through this toolchain but without success. Would you have a suggestion about this?
Again, thanks a lot for your time!

**Comment by blackhole12** [comment]
If `clang` + `wasm-ld` is producing this code, then there is a transformation pass injecting unnecessary indirections somewhere and it's unlikely anything is going to be able to fix it. This means that I either have to create a pass in inNative that undoes this transformation, or allow non-constant values in the indirection.

If you know the constant value of the function you're trying to get, you could manually build a custom webassembly function that gets it for you by injecting something like:
```
(func $getfunc7 (result i32)
  i32.const 7
  call $_innative_funcptr
  return)
```
and then calling this function from whatever you're compiling. Unfortunately there's no way to do this in another module because the function pointer index is per-module.

**Comment by EricSivilog** [comment]
To be honest it would help if in the end we could get the pointer by specifying the function name rather than its index (as you’d do in plain C when specifying a callback). That being said I am still in the prototyping stage of this project, checking if WASM through InNative can meet our requirements. Looks promising! :-)

**Comment by blackhole12** [comment]
Specifying the function name is problematic, because that function name technically doesn't exist in WASM. It is only an optional debug parameter that may or may not exist, and will be stripped when anything happens to drop the optional `name` section in the WASM module. The compiler is supposed to be figuring this stuff out for you, and should provide some way of getting the function index.

**Comment by EricSivilog** [comment]
Do you mean that today’s compilers should already have what I need to solve this problem or that they will eventually when WASM gets more “standardised” interfaces?

**Comment by blackhole12** [comment]
I don't know if compilers are providing a way to do this, I suggest looking into it. If they don't there's very little that inNative can do because inNative is blind to the source language - it doesn't know what you're compiling so all it can do is look at the debug information, which may or may not exist at all.

**Comment by EricSivilog** [comment]
Thanks again for your help - I’ll try to go forward from here and will report back about my findings! :-)

**Comment by blackhole12** [comment]
@EricSivilog While investigating this, it occurred to me that in order to provide an external function that is correctly wrapped for being called from C, this requires that the function be exported from the WASM module. However, if the function is exported from the WASM module, you could simply use `LoadFunction` to get a pointer to the function.

I believe the use-case here was that you want to load a webassembly module, which then returns a function pointer to an internal function that should be called by your C code. Could this module instead return a pointer to a string using `cref` as described in #23? This string could then be used to load the function using `LoadFunction` and remove the need for `_innative_funcptr` entirely.

**Comment by EricSivilog** [comment]
@blackhole12 - Just to give you a more complete picture of what I am trying to achieve:

- I have a Windows DLL which exports a function that takes a function pointer and calls it back at some point.
- From my WASM module, I am calling this function with a function ptr which is actually turned into a function index (as expected).
- I'd like to avoid changing the prototype of the function (because it's been used with a ptr for a long time so switching to a string that contains the function name would break a lot of existing code).

What I've been doing up to now to overcome the issue is to create a proxy DLL between the WASM module and the existing DLL, intercepting calls to this function. I then get the function index, and find its pointer through the "__indirect_function_table" table.

Hope that makes sense!

**Comment by ErikMcClure** [comment]
This function has been changed so that it will work without requiring a constant, and it will always return a pointer to a `__cdecl` wrapper function. However, it can still return `NULL` if you attempt to get a pointer to an _imported_ function (because it doesn't know what calling convention it is). This restriction may be lifted in the future. Intrinsics are now also enabled on any sandboxing setting - you are instead required to use the whitelist to decide what intrinsics to expose to the webassembly module.
