### ISSUE TITLE
str_pair_hash_equal issue

### ISSUE THREAD

**Issue by EricSivilog** [innative-sdk/innative#32]
Hi again !
Still playing with inNative, I think I spotted a small bug in "validate.cpp".
On line 13, we have:
`#define str_pair_hash_equal(a, b) (strcmp(a, b) == 0) && (strcmp(strchr(a, 0)+1, strchr(a, 0)+1) == 0)`
Which I believe should really be:
`#define str_pair_hash_equal(a, b) ((strcmp(a, b) == 0) && (strcmp(strchr(a, 0)+1, strchr(b, 0)+1) == 0))`
The first issue lies in the second strcmp where we were comparing the second part of "a" to itself instead of the second part of "b".
I then realized that I also had to enclose the whole expression between parentheses because of the way "__hash_equal" is used in the KLIB macros. For instance:
`(__ac_isdel(h->flags, i) || !__hash_equal(h->keys[i], key))`
If there are no parentheses around the hash test, we obviously get a wrong result!!
With those two fixes, the issues I had when building my WhiteList are gone ! :)
Thanks again for your work !!!

**Comment by blackhole12** [comment]
I initially thought this would be a quick fix, but this bug was surprisingly difficult to reproduce, because it only happens during a hash collision, which required reverse-engineering a hash collision from the hash function in order to create a test that actually exposed the error. The fix has now been committed and a regression test is now in place.
